# Generated by Django 4.0.1 on 2022-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(max_length=100)),
                ('lastName', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
