# Generated by Django 4.0.1 on 2022-01-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
